<a href="https://colab.research.google.com/github/Lobrenner/PyTorch-Tutorial/blob/main/TensorMathOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
# sub Function

In [10]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [13]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [14]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
#remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [20]:
# Exponents
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [21]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [22]:
#Another way to longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a.sub(tensor_b)

tensor([-4, -4, -4, -4])

In [25]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [26]:
tensor_a

tensor([1, 2, 3, 4])

In [28]:
tensor_a = tensor_a + tensor_b

In [29]:
tensor_a

tensor([11, 14, 17, 20])

In [32]:
tensor_a = torch.tensor([1,2,3,4])
tensor_a

tensor([1, 2, 3, 4])

In [33]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [34]:
tensor_a

tensor([ 6,  8, 10, 12])

In [35]:
tensor_a = torch.tensor([1,2,3,4])
tensor_a

tensor([1, 2, 3, 4])

In [36]:
tensor_a += tensor_b

In [37]:
tensor_a

tensor([ 6,  8, 10, 12])